import { Octokit } from 'octokit'
import type { AppConfig } from '@/types/app'

export interface GithubExportOptions {
  token: string
  repoName: string
  description?: string
  config: AppConfig
  modelDefs: Array<{ name: string; schema: unknown }>
}

export interface GithubExportResult {
  repoUrl: string
  success: boolean
  error?: string
}

export async function exportToGithub(options: GithubExportOptions): Promise<GithubExportResult> {
  const { token, repoName, description, config, modelDefs } = options

  try {
    const octokit = new Octokit({ auth: token })

    // Get the authenticated user
    const { data: user } = await octokit.rest.users.getAuthenticated()

    // Create the repository
    let repo
    try {
      const { data } = await octokit.rest.repos.createForAuthenticatedUser({
        name: repoName,
        description: description ?? `Generated by AI App Generator - ${config.name}`,
        private: false,
        auto_init: false,
      })
      repo = data
    } catch (err: unknown) {
      // If repo exists, use it
      if ((err as { status?: number }).status === 422) {
        const { data } = await octokit.rest.repos.get({
          owner: user.login,
          repo: repoName,
        })
        repo = data
      } else {
        throw err
      }
    }

    // Generate file contents
    const files = generateAppFiles(config, modelDefs)

    // Create a tree with all files
    const blobs = await Promise.all(
      files.map(async (file) => {
        const { data: blob } = await octokit.rest.git.createBlob({
          owner: user.login,
          repo: repoName,
          content: Buffer.from(file.content).toString('base64'),
          encoding: 'base64',
        })
        return {
          path: file.path,
          mode: '100644' as const,
          type: 'blob' as const,
          sha: blob.sha,
        }
      })
    )

    // Get or create base tree
    let baseTreeSha: string | undefined
    try {
      const { data: ref } = await octokit.rest.git.getRef({
        owner: user.login,
        repo: repoName,
        ref: 'heads/main',
      })
      baseTreeSha = ref.object.sha
    } catch {
      // No commits yet, start fresh
    }

    const { data: tree } = await octokit.rest.git.createTree({
      owner: user.login,
      repo: repoName,
      tree: blobs,
      base_tree: baseTreeSha,
    })

    // Create commit
    const { data: commit } = await octokit.rest.git.createCommit({
      owner: user.login,
      repo: repoName,
      message: `feat: export ${config.name} app configuration`,
      tree: tree.sha,
      parents: baseTreeSha ? [baseTreeSha] : [],
    })

    // Update or create the main branch
    try {
      await octokit.rest.git.updateRef({
        owner: user.login,
        repo: repoName,
        ref: 'heads/main',
        sha: commit.sha,
      })
    } catch {
      await octokit.rest.git.createRef({
        owner: user.login,
        repo: repoName,
        ref: 'refs/heads/main',
        sha: commit.sha,
      })
    }

    return { repoUrl: repo.html_url, success: true }
  } catch (err) {
    const message = err instanceof Error ? err.message : 'Unknown error occurred'
    return { repoUrl: '', success: false, error: message }
  }
}

function generateAppFiles(
  config: AppConfig,
  modelDefs: Array<{ name: string; schema: unknown }>
) {
  return [
    {
      path: 'README.md',
      content: generateReadme(config),
    },
    {
      path: 'app-config.json',
      content: JSON.stringify(config, null, 2),
    },
    {
      path: 'schemas/models.json',
      content: JSON.stringify(modelDefs, null, 2),
    },
    {
      path: 'package.json',
      content: generatePackageJson(config),
    },
    {
      path: '.env.example',
      content: `DATABASE_URL="postgresql://username:password@localhost:5432/${config.name.toLowerCase().replace(/\s+/g, '_')}"\nNEXTAUTH_SECRET="your-secret"\nNEXTAUTH_URL="http://localhost:3000"\n`,
    },
    {
      path: 'prisma/schema.prisma',
      content: generatePrismaSchema(modelDefs),
    },
  ]
}

function generateReadme(config: AppConfig): string {
  return `# ${config.name}

${config.description ?? 'Generated with AI App Generator'}

## Getting Started

1. Clone this repository
2. Copy \`.env.example\` to \`.env.local\` and fill in your values
3. Run \`npm install\`
4. Run \`npx prisma db push\`
5. Run \`npm run dev\`

## App Configuration

This app was generated from the following configuration:

\`\`\`json
${JSON.stringify(config, null, 2)}
\`\`\`

## Generated with

[AI App Generator](https://github.com/ai-app-generator) — A metadata-driven application runtime.
`
}

function generatePackageJson(config: AppConfig): string {
  return JSON.stringify(
    {
      name: config.name.toLowerCase().replace(/\s+/g, '-'),
      version: '0.1.0',
      private: true,
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start',
        lint: 'next lint',
      },
      dependencies: {
        next: '^14.0.0',
        react: '^18.0.0',
        'react-dom': '^18.0.0',
        '@prisma/client': '^5.0.0',
        'next-auth': '^5.0.0',
        zod: '^3.0.0',
      },
      devDependencies: {
        prisma: '^5.0.0',
        typescript: '^5.0.0',
        '@types/node': '^20.0.0',
        '@types/react': '^18.0.0',
      },
    },
    null,
    2
  )
}

function generatePrismaSchema(modelDefs: Array<{ name: string; schema: unknown }>): string {
  return `generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

// Dynamic records stored as JSONB
model Record {
  id        String   @id @default(cuid())
  model     String   // Model name (${modelDefs.map((m) => m.name).join(', ')})
  data      Json     // Record data
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  @@map("records")
}

// Model definitions for validation
model ModelDef {
  id     String @id @default(cuid())
  name   String @unique
  schema Json

  @@map("model_defs")
}
`
}
